#HOTFIX: boost::STATIC_ASSERTION_FAILURE  (boost >1.37)
Ubuntu 16.04.3 LTS (Xenial Xerus) + boost >1.37

typename boost::add_reference<T>::type = const CScriptID&]' rpcrawtransaction.cpp:243:77: required from here
/usr/include/boost/variant/get.hpp:178:5: error: invalid application of 'sizeof' to incomplete type 'boost::STATIC_ASSERTION_FAILURE<false>'
     BOOST_STATIC_ASSERT_MSG(
     ^
makefile.unix:187: recipe for target 'obj/rpcrawtransaction.o' failed
make: *** [obj/rpcrawtransaction.o] Error 1